#! /bin/sh

# keybind manager
sxhkd &

# mouse focus
bspc config focus_follows_pointer true

# window configurations
bspc config top_padding          32
bspc config border_width         1
bspc config window_gap           16
bspc config normal_border_color  \#31313f
bspc config active_border_color  \#31313f
bspc config focused_border_color \#ebebff

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# setup for multiple monitors
bspc monitor DVI-I-1 -d browser android blank blank music
bspc monitor DP-1 -d code server blank telegram wiki

# rules
bspc rule -a "" desktop='^5'
bspc rule -a Firefox desktop='^1'

# programs to run during startup
sh ~/.fehbg &
polybar bar1 &
polybar bar2 &
xsetroot -cursor_name left_ptr &
#compton &

